#!/bin/bash

# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)

# Absolute path this script is in. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

echo "linking files..."
echo "- vimrc"
ln -sf $SCRIPTPATH/vimrc ~/.vimrc
echo "- zshrc"
ln -sf $SCRIPTPATH/zshrc ~/.zshrc
echo "- bashrc"
ln -sf $SCRIPTPATH/bashrc ~/.bashrc
echo "- tmux.conf"
ln -sf $SCRIPTPATH/tmux.conf ~/.tmux.conf
echo "- vim/"
ln -sf $SCRIPTPATH/vim ~/.vim
